# Exercise 4
---
Course: Scientific Programming<br>
Date: 02.04.2022<br>
Author: Erinc Emre Celikten<br>
Author School Number: 20170808032

---

## 9 Numpy

In [54]:
import numpy as np
import scipy as sp

n = 200
m = 500

k = np.random.rand(m)
l = np.random.rand(m)

A = np.random.normal(0,1, (n,m))
B = sp.linalg.toeplitz(k,l)

print('Matrix A:' , A)
print('Matrix B:' , B)

Matrix A: [[ 0.25595193  0.82809354  0.88604582 ... -0.78902968  0.72797837
  -0.55808242]
 [ 0.23227638 -1.06379514 -0.29596069 ... -1.46898356  0.84551946
  -0.00369257]
 [ 0.91685539 -0.94991889  0.35570188 ... -0.99938515 -1.07980852
   0.35026596]
 ...
 [-0.95102709 -0.04375798  0.25821188 ...  0.63771571  0.17208897
   1.15964911]
 [-1.33177325  0.56418558  0.47407126 ... -0.39497669 -1.47024978
  -0.58419663]
 [-0.7067997   0.26944918 -1.31776586 ...  0.35365681  0.01657346
  -0.93741665]]
Matrix B: [[0.50036567 0.36023095 0.30310649 ... 0.46099971 0.28124473 0.40985005]
 [0.18618189 0.50036567 0.36023095 ... 0.36739984 0.46099971 0.28124473]
 [0.36410016 0.18618189 0.50036567 ... 0.10218393 0.36739984 0.46099971]
 ...
 [0.45803691 0.3414293  0.69485358 ... 0.50036567 0.36023095 0.30310649]
 [0.85157841 0.45803691 0.3414293  ... 0.18618189 0.50036567 0.36023095]
 [0.96065014 0.85157841 0.45803691 ... 0.36410016 0.18618189 0.50036567]]


## 9.1: Matrix operations

In [12]:
print('A + A = ', A + A)

A + A =  [[ 7.17071949e-01 -4.36598307e-01 -2.51916761e+00 ...  1.03079220e+00
   1.73660683e+00  2.01581108e-01]
 [ 2.01031480e+00  9.91879849e-01  6.31479873e-02 ...  8.36164610e-01
   8.79682529e-01  1.15552033e+00]
 [-2.09827006e+00 -1.84161329e+00  6.08143425e-01 ...  2.93500545e+00
   1.00060516e+00  7.86884246e-01]
 ...
 [-1.12859321e+00  1.29406491e+00  4.48824320e-01 ...  1.63566636e+00
  -1.93449667e+00  1.16750492e+00]
 [ 2.96239567e+00 -2.54970341e-01  2.11125644e+00 ... -1.95106381e+00
  -1.45901394e+00 -8.02895353e-01]
 [ 1.94771277e-03 -1.35550315e+00 -9.27656337e-01 ...  1.77054050e+00
  -1.09925204e+00  6.30569070e-01]]


In [14]:
print('A A^T = ', np.dot(A, A.T))

A A^T =  [[505.71147362   4.1922095  -14.09588808 ... -39.38952933   5.62093738
  -17.38418776]
 [  4.1922095  485.34125482  -9.74521184 ...  11.29628028 -17.88822214
   -7.38637597]
 [-14.09588808  -9.74521184 469.19003059 ...  -3.84335075 -34.43135529
   28.77151338]
 ...
 [-39.38952933  11.29628028  -3.84335075 ... 476.14011219  -2.23346272
  -16.32134331]
 [  5.62093738 -17.88822214 -34.43135529 ...  -2.23346272 528.27586766
   -2.32758893]
 [-17.38418776  -7.38637597  28.77151338 ... -16.32134331  -2.32758893
  449.80339062]]


In [15]:
print('A^T  A = ', np.dot(A.T, A))

A^T  A =  [[ 1.86630624e+02  5.78165765e+00 -1.01434078e+01 ...  2.94846222e+00
   6.81339110e+00  1.28920682e+00]
 [ 5.78165765e+00  1.58888743e+02 -1.87645942e+00 ... -6.17782122e+00
   7.82648991e+00 -6.32140368e+00]
 [-1.01434078e+01 -1.87645942e+00  1.72451241e+02 ...  1.83404787e+01
   4.30876087e+00 -1.26333487e+01]
 ...
 [ 2.94846222e+00 -6.17782122e+00  1.83404787e+01 ...  1.66140586e+02
   1.05854725e-01  1.79849723e+01]
 [ 6.81339110e+00  7.82648991e+00  4.30876087e+00 ...  1.05854725e-01
   2.43061022e+02  1.05195814e+01]
 [ 1.28920682e+00 -6.32140368e+00 -1.26333487e+01 ...  1.79849723e+01
   1.05195814e+01  1.82452827e+02]]


In [16]:
print('AB = ', np.dot(A, B))

AB =  [[ -3.44400055 -11.642988    -9.27447954 ... -22.65251142  -7.49379736
  -23.44343094]
 [  8.15135555  10.87761272   4.63964503 ...  21.11363732   7.8528988
   11.26613937]
 [ -8.88432098 -22.30332738 -16.99319738 ... -10.44124807 -11.12919143
   -8.0877157 ]
 ...
 [ -2.17610882 -15.03816867 -12.8279838  ...  -2.80220149 -17.00771397
    3.72952965]
 [ -4.81410848   8.36969293 -10.17995254 ...  -3.48558591   4.84138658
  -15.19389908]
 [ 21.18176075  21.58863902  18.52679993 ...  23.83377527  19.33842934
   12.78235362]]


In [22]:
def func(A, B, Lam):
    temp = B - Lam*np.eye(m)
    return np.dot(A, temp)


print('A(B − λI) for λ:12 =', func(A,B, 12))

A(B − λI) for λ:12 = [[ -7.74643225  -9.02339816   5.84052612 ... -28.83726464 -17.91343833
  -24.65291759]
 [ -3.91053327   4.92633363   4.2607571  ...  16.09664966   2.57480363
    4.33301739]
 [  3.70529941 -11.25364762 -20.64205793 ... -28.05128077 -17.1328224
  -12.80902117]
 ...
 [  4.59545046 -22.80255815 -15.52092972 ... -12.61619968  -5.40073395
   -3.2754999 ]
 [-22.58848252   9.89951498 -22.84749117 ...   8.22079693  13.59547022
  -10.37652696]
 [ 21.17007447  29.7216579   24.09273795 ...  13.21053228  25.93394161
    8.9989392 ]]


## 9.2: Solving a linear system

In [37]:
b = np.random.rand(m,1)
print('x of Bx=b, where b is a random vector ', np.linalg.solve(B, b))

x of Bx=b, where b is a random vector  [[-3.43212203e-01]
 [ 3.07451684e-01]
 [ 3.69373609e-01]
 [ 6.22607994e-02]
 [ 3.14868182e-01]
 [-9.59887845e-02]
 [-1.77866255e-01]
 [-5.92157118e-01]
 [ 2.27398062e-01]
 [-9.31854389e-02]
 [ 6.11276737e-01]
 [-4.10882877e-01]
 [-5.15174762e-01]
 [ 2.27625501e-01]
 [-2.89482344e-01]
 [ 5.36339402e-01]
 [ 1.93985529e-01]
 [-4.79489758e-01]
 [ 3.14831627e-01]
 [-3.86988512e-01]
 [-1.35769669e-01]
 [ 4.32166136e-01]
 [-3.26193272e-01]
 [-6.24627396e-01]
 [-4.15712253e-01]
 [ 2.44003484e-01]
 [ 2.55447506e-01]
 [-6.45384674e-01]
 [-6.13901670e-01]
 [ 1.44581429e-01]
 [-1.02827070e-01]
 [ 3.45723615e-01]
 [ 6.98964108e-01]
 [-3.90166143e-01]
 [-2.80161775e-01]
 [-2.80487107e-02]
 [ 3.77231507e-01]
 [ 5.62835965e-01]
 [-3.73190597e-01]
 [-8.87133107e-03]
 [-8.96437439e-01]
 [-2.29535267e-02]
 [ 9.88770176e-01]
 [-3.09115708e-01]
 [-1.10172755e-01]
 [-2.19009814e-01]
 [-7.39084519e-02]
 [-2.01633283e-01]
 [ 1.74758850e-01]
 [ 1.04767875e+00]
 [-5.591920

## 9.3: Norms

In [52]:
print('Frobenius norm: ', np.linalg.norm(A))
print('max(sum(abs(x), axis=1)): ', np.linalg.norm(B, ord=np.inf))
print('2-norm (largest sing. value): ', np.linalg.norm(B, ord=2))
print('smallest singular value: ', np.linalg.norm(B, ord=-2))

Frobenius norm:  315.19161758670623
max(sum(abs(x), axis=1)):  257.2038741483394
2-norm (largest sing. value):  249.99970126544463
smallest singular value:  0.043996193974349423


## 9.4: Power iteration

In [78]:
import time

def timer(funcx):
    def wrapper():
        start = time.time()
        funcx()
        end = time.time()
        print('Opertaion takes', end - start, 'seconds')

    return wrapper


@timer
def func4():
    Z = np.random.normal(2,2, (n, n))
    w, v = np.linalg.eig(Z)
    print('Largest eigenvalue: ', w.max())
    print('Corresponding eigenvector: ', v) 

func()



Largest eigenvalue:  (402.5679828651364+0j)
Corresponding eigenvector:  [[ 0.07352376+0.j         -0.07500936+0.j          0.01506114+0.04187568j
  ...  0.00836858+0.00296743j -0.0284799 +0.j
  -0.02285704+0.j        ]
 [ 0.07339198+0.j         -0.05182168+0.j         -0.01106417-0.04054018j
  ...  0.07379559+0.01401192j -0.01334886+0.j
  -0.02252895+0.j        ]
 [ 0.06710944+0.j         -0.06804143+0.j          0.0295543 +0.02690085j
  ... -0.07366597-0.03370978j  0.1064735 +0.j
   0.12308099+0.j        ]
 ...
 [ 0.07048214+0.j          0.03647313+0.j          0.03959005-0.00648595j
  ...  0.021406  +0.01627214j -0.09931681+0.j
  -0.09023834+0.j        ]
 [ 0.06652075+0.j          0.0024151 +0.j          0.06919537+0.12779102j
  ...  0.08758211+0.05933558j -0.05193183+0.j
  -0.08080466+0.j        ]
 [ 0.07427481+0.j         -0.05399716+0.j         -0.04191569+0.04515857j
  ... -0.01295197-0.00871226j  0.07124857+0.j
   0.048965  +0.j        ]]
Opertaion takes 0.04139995574951172 seco

## 9.6: Nearest neighbor

In [82]:
def func6(A, z):
    A = np.asarray(A)
    idx = (np.abs(A - z)).argmin()
    return A[idx]

A = np.random.rand(10)
z = 0
print('For matrix A:\n', A, '\nnearest element to z=0 is :', func6(A, z))

For matrix A:
 [0.41470182 0.1035325  0.75663856 0.58833576 0.59381423 0.37108522
 0.72677941 0.28817796 0.38955398 0.81723784] 
nearest element to z=0 is : 0.10353249768233752
